/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanicRouteImport } from './routes/panic'
import { Route as IndexRouteImport } from './routes/index'

const PanicRoute = PanicRouteImport.update({
  id: '/panic',
  path: '/panic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panic': typeof PanicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panic': typeof PanicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panic': typeof PanicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/panic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/panic'
  id: '__root__' | '/' | '/panic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanicRoute: typeof PanicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panic': {
      id: '/panic'
      path: '/panic'
      fullPath: '/panic'
      preLoaderRoute: typeof PanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanicRoute: PanicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
